app/urls.py
from django.urls import path
from .views import home_page, ItemDetailView, ItemFilterView, MyView, ajax_post_add, PostList
from django.conf.urls import include, url


app_name = "app"


urlpatterns = [
    path("", ItemFilterView.as_view(), name="home"),
    path('detail/<int:pk>/', ItemDetailView.as_view(), name='detail'),
    path('user/', MyView.as_view(), name='user'),
    path("ajax/", ajax_post_add, name="ajax_post_add"),
    path("ajax_test/", PostList.as_view(), name="ajax_test"),
]

south_scripts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

app/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Season(models.Model):

    season = models.CharField(
        verbose_name='シーズン',
        max_length=200,
    )


class Title(models.Model):

    season = models.ForeignKey(Season, on_delete=models.CASCADE)

    title = models.CharField(
        verbose_name='タイトル',
        max_length=200,
    )

    url = models.URLField(
        verbose_name='URL',
        max_length=200,
        default="",
    )

    @property
    def season_is(self):
        return self.season.season




class Item(models.Model):

    title = models.ForeignKey(Title, on_delete=models.CASCADE, blank=True, null=True)

    progress = models.IntegerField(
        verbose_name='進行度',
        blank=True,
        null=True,
    )

    speaker = models.CharField(
        verbose_name='発話者',
        max_length=200,
    )

    script = models.TextField(
        verbose_name='セリフ',
        max_length=1000,
        blank=True,
        null=True,
    )

    @property
    def title_is(self):
        return self.title.title


class User(models.Model):
    name = models.CharField(max_length=128)
    scripts = models.ManyToManyField(Item)

    def __str__(self):
        return self.name


class Profile(models.Model):
    name = models.CharField("名前", max_length=255)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    scripts = models.ManyToManyField(Item, blank=True, through='Quote')

    def __str__(self):
        return self.name

    def my_function(self):
        # Return some calculated value based on the entry
        my_value = "korede"
        return my_value


class Post(models.Model):
    title = models.CharField('タイトル', max_length=255)

    def __str__(self):
        return self.title


class Quote(models.Model):
        script = models.ForeignKey(Item, on_delete=models.CASCADE, blank=True)
        owner = models.ForeignKey(Profile, on_delete=models.CASCADE)
        date_joined = models.DateField(auto_now_add=True)

        def get_script(self):
            script = self.script.script
            return script

        def get_speaker(self):
            speaker = self.script.speaker
            return speaker

        def get_id(self):
            i_id = self.script.pk
            return i_id




app/templates/_pagination.html
{% load item_extras %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item pagination-prev">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link">&laquo;</span>
        </li>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active page-item">
                    <span class="page-link">{{ page }}
                        <span class="page-link sr-only">(current)</span>
                    </span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{% url_replace request 'page' page %}">{{ page }}</a>
                </li>
            {% endifequal %}
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item pagination-next">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link ">&raquo;</span>
        </li>
    {% endif %}
</ul>

app/templates/ajax_bookmark.html
{% block extrajs %}
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        // 送信ボタンで呼ばれる
        $("#boke").click('submit', e => {
            // デフォルトのイベントをキャンセルし、ページ遷移しないように!
            e.preventDefault();

            $.ajax({
                'url': '{% url "app:ajax_post_add" %}',
                'type': 'POST',
                'data': {
                    <!--'title': $('#id_title').val(),  // 記事タイトル-->
                    'item_id': '{{item.pk}}'
                },
                'dataType': 'json'
            }).done( response => {
                // <p>はろー</p>のような要素を作成し、それを記事一覧エリアに追加し、入力欄をクリアする。
                alert("ajax!!");

            });

        });
    </script>


{% endblock %}

app/templates/ajax_test.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Ajaxのれんしゅう</title>
  </head>
  <body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% include './post_list.html' %}
  </body>
</html>

app/templates/base.html
{% load static %}
<html>
<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>アプリケーション名</title>
    <!-- Bootstrap CSS -->
<!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
    <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!--<script src="{% static 'app/js/bootstrap.js' %}"></script>-->
    <link href="{% static 'app/css/app.css' %}" rel="stylesheet">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'app:home'%}">アプリケーション名</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false"
            aria-label="ナビゲーションの切替">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="Navber">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index'%}">管理サイト</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout'%}">ログアウト</a>
                </li>
                                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login'%}">ログインテスト</a>
                </li>
                    {% if user.is_authenticated %}
                                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login'%}">{{user.username}}でログイン成功</a>
                </li>
                               <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout'%}">{{user.name}}ログアウトしよう</a>
                </li>
                    {% endif %}
                                            <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:user'%}">ユーザーページ</a>
                </li>
                                          <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:ajax_test'%}">Ajaxテスト</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>
    <div class="container" >

<div class="mt-5">検索してね</div>
        <hoge class="huga">test</hoge>

    <div>{% block content %}</div>

    <div>{% endblock %}</div>
    </div>


    <script>
      $(".show-popover").on('click', function () {
  $("#myPopover").popover('show');
});</script>

<script src="{% static 'app/js/app.js' %}"></script>
  <script src="{% static 'app/js/pop_for_non_user.js' %}"></script>

<script>
    $("button.btn-danger").after('{% csrf_token %}')


</script>
<script>
$(function() {
  $('.del_confirm').on('click', function () {
  console.log("ulyyyyy");
    console.log(($(this).data("pk")));
     $("#del_pk").text($(this).data("pk"));
     $('#del_url').attr('value', $(this).data("pk"));
  });
});
</script>
    <link href="{% static 'app/css/danger.css' %}" rel="stylesheet">
</body>
</html>

app/templates/item_detail.html

{% extends "./base.html" %}
{% load item_extras %}
{% load static %}
{% block content %}
<div class="container">


<div class="jumbotron" style="width:30rem;">
  <h1 class="display-4">{% replace_underbar item.title.title %}</h1>
  <p class="lead">This is a simple hero unit ...</p>
  <hr class="my-4">
  <p>It uses utility classes for ...</p>
  <a class="btn btn-primary btn-lg" href="{{ item.title.url }}" role="button">Watch Episode!</a>
</div>


    <div class="container">

  <section>
          {% if user.is_authenticated %}
        {% if bookmarked == True %}
          <p>
      <button type="button" class="btn btn-default hogeo disable" data-toggle="popover" data-content="お気に入りリストに追加しました"  data-placement="top" id="boke"
      action="{% url 'app:ajax_post_add' %}" method="submit">
        <span class="glyphicon glyphicon-heart text-danger" aria-hidden="true"></span>お気に入りに追加済みです
      </button>
    </p>
        {% else %}
          <p>
      <button type="button" class="btn btn-default hogeo" data-toggle="popover" data-content="お気に入りリストに追加しました"  data-placement="top" id="boke"
      action="{% url 'app:ajax_post_add' %}" method="submit">
        <span class="glyphicon glyphicon-heart text-danger" aria-hidden="true"></span>お気に入りに追加
      </button>
    </p>
    <p>クリックするとポップアップが表示され、ポップアップ内に追加されたメッセージが表示され、3秒後にポップアップが消え、ボタンがクリック出来なくなります。</p>
    {% endif %}
      {% else %}
 <button type="button" class="btn btn-default hogeo" data-toggle="popover" data-content="ユーザー登録が必要です"  data-placement="top" id="non_user"
      action="{% url 'app:ajax_post_add' %}" method="submit">
        <span class="glyphicon glyphicon-heart text-danger" aria-hidden="true"></span>お気に入りに追加
      </button>

      {% endif %}




  </section>




<button id="buta">ボタン</button>

</div>

    <p>

  <a href="#" data-toggle="popover" id="myPopover" data-content="ココにポップオーバーが表示">ポップオーバーの実例</a>
</p>
  <div>
    <p>ポップオーバーを手動で制御するには、以下のボタンを押す。</p>
    <input type="button" class="btn btn-primary show-popover" value="表示">
    <input type="button" class="btn btn-warning hide-popover" value="隠す">
    <input type="button" class="btn btn-success toggle-popover" value="切替">
    <input type="button" class="btn btn-danger dispose-popover" value="破棄">
  </div>



    {% include './ajax_bookmark.html' %}
  <!--<script src="{% static 'app/js/check_book.js' %}"></script>-->
</div>
{% endblock %}

app/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
No result
</body>
</html>

app/templates/post_list.html
{% block content %}
    <h2>記事一覧</h2>
    <div id="posts">
        {% for post in post_list %}
            <p>{{ post.title }}</p>
        {% endfor %}
    </div>

    <hr>

    <h2>記事の追加</h2>
    <form id="ajax-add-post" action="{% url 'app:ajax_post_add' %}" method="POST">
        <input type="text" id="id_title" required>
        <button type="submit" >送信</button>
        {% csrf_token %}
    </form>

{% endblock %}

{% block extrajs %}
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        // 送信ボタンで呼ばれる
        $('#ajax-add-post').on('submit', e => {
            // デフォルトのイベントをキャンセルし、ページ遷移しないように!
            e.preventDefault();

            $.ajax({
                'url': '{% url "app:ajax_post_add" %}',
                'type': 'POST',
                'data': {
                    'title': $('#id_title').val(),  // 記事タイトル
                },
                'dataType': 'json'
            }).done( response => {
                // <p>はろー</p>のような要素を作成し、それを記事一覧エリアに追加し、入力欄をクリアする。
                const p = $('<p>', {text: response.title});
                $('#posts').prepend(p);
                $('#id_title').val('');
            });

        });
    </script>


{% endblock %}

app/templates/profile_list.html
{% extends "./base.html" %}

{% block content %}
{% load crispy_forms_tags %}
<header class="sticky-top" id="sticky">
    				<form id="filter" method="get">
					<div class="modal-body">
						{{filter.form|crispy}}
					</div>
				</form>

</header>
<div class="container" id="hogehoge">
    <hr>

    {% if get_flag == True %}
    {% if profile_list == False%}
    <a>no result</a>
    {% endif %}
    		<div class="col-12">
			{% include "./_pagination.html" %}
		</div>
    {% for item in item_list %}

<span style="text-align:center; font-weight:bold">
{{item.speaker}}
</span>
<div class="inline-block_test">{{ item.script |truncatewords:15}}</div>
        <a href="{% url 'app:detail' item.pk %}"> show detail </a>

        <hr>

    {% endfor %}
    {% endif %}
</div>
{% endblock %}

app/templates/user.html

{% extends "./base.html" %}
{% load item_extras %}
{% load static %}
{% load render_table from django_tables2 %}
{% block content %}

<a>{{user.username}}</a>



{% for script in scripts %}
<a>---------</a>
{{script.title_is}}
{{script.speaker}}
{% endfor %}


{% if is_empty == False %}

{% render_table table %}
{% else %}
<a href="{% url 'app:home'%}">お気に入りのセリフを登録しよう！</a>
{% endif %}

<!--<a href="../detail/1/">詳細<a>-->



    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">確認</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">
            <p>削除してよろしいですか？</p>
          </div>
          <div class="modal-footer">
            <form name="action" method="POST"><button type="submit" name="b_name" class="btn btn-primary" value="" id="del_url">OK</button>
            {% csrf_token %}
            </form>
            <form>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              </form>
          </div>
        </div>
      </div>
    </div>



<a class="fugafuga">aaaaaaaaaaaaaa</a>






{% endblock %}